// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: cyservice.proto
#ifndef GRPC_cyservice_2eproto__INCLUDED
#define GRPC_cyservice_2eproto__INCLUDED

#include "cyservice.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace cyservice {

class CyService GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::cyservice::Fragment, ::cyservice::Fragment>> StreamFragments(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::cyservice::Fragment, ::cyservice::Fragment>>(StreamFragmentsRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cyservice::Fragment, ::cyservice::Fragment>> AsyncStreamFragments(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::cyservice::Fragment, ::cyservice::Fragment>>(AsyncStreamFragmentsRaw(context, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::cyservice::Fragment, ::cyservice::Fragment>* StreamFragmentsRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::cyservice::Fragment, ::cyservice::Fragment>* AsyncStreamFragmentsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>> StreamFragments(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>>(StreamFragmentsRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>> AsyncStreamFragments(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>>(AsyncStreamFragmentsRaw(context, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>* StreamFragmentsRaw(::grpc::ClientContext* context) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>* AsyncStreamFragmentsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_StreamFragments_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamFragments(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamFragments : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_StreamFragments() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamFragments() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamFragments(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>* stream) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamFragments(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamFragments<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_StreamFragments : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_StreamFragments() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamFragments() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamFragments(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::cyservice::Fragment, ::cyservice::Fragment>* stream) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace cyservice


#endif  // GRPC_cyservice_2eproto__INCLUDED
